[package]
name = "labx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "*"
quick-xml = "0.27.1"
serde-xml-rs ="0.6.0"
serde={version = "*", features=["derive"]}